import { storage } from "./storage";
import type { InsertRestaurant, InsertMenuItem } from "@shared/schema";

export async function seedRestaurants() {
  const restaurants: Omit<InsertRestaurant, 'userId'>[] = [
    {
      name: "Evergreen",
      description: "Fresh and healthy vegetarian cuisine with organic ingredients",
      cuisine: "Vegetarian",
      businessLicense: "VEG001",
      campusLocation: "Main Campus - Food Court",
      deliveryTime: "25-35 min",
      priceForTwo: 400,
      imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800",
      rating: "4.5",
      isActive: true,
      minimumOrder: 150,
      preparationTime: 20,
    },
    {
      name: "Queen's Court",
      description: "Royal Indian cuisine with authentic flavors and spices",
      cuisine: "Indian",
      businessLicense: "IND001",
      campusLocation: "Academic Block - Ground Floor",
      deliveryTime: "30-45 min",
      priceForTwo: 600,
      imageUrl: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800",
      rating: "4.7",
      isActive: true,
      minimumOrder: 200,
      preparationTime: 25,
    },
    {
      name: "Zinger",
      description: "Crispy fried chicken and spicy wings that pack a punch",
      cuisine: "Fast Food",
      businessLicense: "FF001",
      campusLocation: "Student Center",
      deliveryTime: "20-30 min",
      priceForTwo: 500,
      imageUrl: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=800",
      rating: "4.3",
      isActive: true,
      minimumOrder: 150,
      preparationTime: 15,
    },
    {
      name: "Butty Sandwich",
      description: "Gourmet sandwiches, wraps and burgers made to order",
      cuisine: "Continental",
      businessLicense: "CON001",
      campusLocation: "Library Block",
      deliveryTime: "15-25 min",
      priceForTwo: 350,
      imageUrl: "https://images.unsplash.com/photo-1539252554453-80ab65ce3586?w=800",
      rating: "4.4",
      isActive: true,
      minimumOrder: 100,
      preparationTime: 12,
    },
    {
      name: "Duck Donald",
      description: "Authentic Chinese cuisine with duck specialties and noodles",
      cuisine: "Chinese",
      businessLicense: "CHN001",
      campusLocation: "Hostel Complex",
      deliveryTime: "35-45 min",
      priceForTwo: 550,
      imageUrl: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800",
      rating: "4.6",
      isActive: true,
      minimumOrder: 180,
      preparationTime: 30,
    },
    {
      name: "Shakes & Desserts",
      description: "Creamy milkshakes, ice creams and delightful desserts",
      cuisine: "Desserts",
      businessLicense: "DES001",
      campusLocation: "Recreation Center",
      deliveryTime: "10-20 min",
      priceForTwo: 300,
      imageUrl: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800",
      rating: "4.8",
      isActive: true,
      minimumOrder: 80,
      preparationTime: 8,
    },
    {
      name: "Yurish Drinks",
      description: "Fresh juices, smoothies and healthy beverages",
      cuisine: "Beverages",
      businessLicense: "BEV001",
      campusLocation: "Sports Complex",
      deliveryTime: "5-15 min",
      priceForTwo: 250,
      imageUrl: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800",
      rating: "4.5",
      isActive: true,
      minimumOrder: 60,
      preparationTime: 5,
    },
  ];

  // Create a default user for restaurants
  const restaurantUser = await storage.createUser({
    email: "restaurants@campuseats.com",
    password: "password123",
    role: "restaurant",
    name: "Restaurant Owner",
    phone: "+91-9876543210",
  });

  const createdRestaurants = [];
  for (const restaurant of restaurants) {
    const created = await storage.createRestaurant({
      ...restaurant,
      userId: restaurantUser.id,
    });
    createdRestaurants.push(created);
  }

  return createdRestaurants;
}

export async function seedMenuItems(restaurants: any[]) {
  const menuItems: { [key: string]: Omit<InsertMenuItem, 'restaurantId'>[] } = {
    "Evergreen": [
      {
        name: "Paneer Butter Masala",
        description: "Creamy tomato-based curry with soft paneer cubes",
        price: "280",
        category: "Main Course",
        dietaryTags: ["Vegetarian"],
        allergens: ["Dairy"],
        nutritionInfo: { calories: 450, protein: 18, carbs: 25, fat: 32 },
        preparationTime: 20,
        spiceLevel: 2,
        isAvailable: true,
        isPopular: true,
      },
      {
        name: "Dal Tadka",
        description: "Yellow lentils tempered with cumin and spices",
        price: "180",
        category: "Main Course",
        dietaryTags: ["Vegetarian", "Vegan", "Gluten-Free"],
        nutritionInfo: { calories: 220, protein: 12, carbs: 35, fat: 6 },
        preparationTime: 15,
        spiceLevel: 1,
        isAvailable: true,
      },
      {
        name: "Vegetable Biryani",
        description: "Fragrant basmati rice with mixed vegetables and spices",
        price: "320",
        category: "Rice",
        dietaryTags: ["Vegetarian"],
        allergens: ["Nuts"],
        nutritionInfo: { calories: 380, protein: 10, carbs: 65, fat: 12 },
        preparationTime: 25,
        spiceLevel: 2,
        isAvailable: true,
        isPopular: true,
      },
      {
        name: "Green Salad",
        description: "Fresh mixed greens with cucumber, tomato and lemon dressing",
        price: "120",
        category: "Salads",
        dietaryTags: ["Vegetarian", "Vegan", "Gluten-Free"],
        nutritionInfo: { calories: 80, protein: 3, carbs: 12, fat: 2 },
        preparationTime: 5,
        spiceLevel: 0,
        isAvailable: true,
      },
      {
        name: "Masala Chai",
        description: "Traditional Indian tea with aromatic spices",
        price: "40",
        category: "Beverages",
        dietaryTags: ["Vegetarian"],
        allergens: ["Dairy"],
        nutritionInfo: { calories: 120, protein: 4, carbs: 18, fat: 3 },
        preparationTime: 5,
        spiceLevel: 1,
        isAvailable: true,
      },
    ],
    "Queen's Court": [
      {
        name: "Chicken Tikka Masala",
        description: "Grilled chicken in rich tomato and cream sauce",
        price: "380",
        category: "Main Course",
        allergens: ["Dairy"],
        nutritionInfo: { calories: 520, protein: 35, carbs: 15, fat: 35 },
        preparationTime: 25,
        spiceLevel: 3,
        isAvailable: true,
        isPopular: true,
      },
      {
        name: "Mutton Rogan Josh",
        description: "Slow-cooked lamb in aromatic Kashmiri spices",
        price: "450",
        category: "Main Course",
        allergens: ["Dairy"],
        nutritionInfo: { calories: 480, protein: 38, carbs: 12, fat: 30 },
        preparationTime: 35,
        spiceLevel: 4,
        isAvailable: true,
        isPopular: true,
      },
      {
        name: "Tandoori Chicken",
        description: "Marinated chicken grilled in clay oven",
        price: "320",
        category: "Starters",
        allergens: ["Dairy"],
        nutritionInfo: { calories: 280, protein: 40, carbs: 8, fat: 10 },
        preparationTime: 20,
        spiceLevel: 3,
        isAvailable: true,
      },
      {
        name: "Garlic Naan",
        description: "Soft bread topped with garlic and herbs",
        price: "80",
        category: "Breads",
        dietaryTags: ["Vegetarian"],
        allergens: ["Gluten", "Dairy"],
        nutritionInfo: { calories: 180, protein: 6, carbs: 28, fat: 6 },
        preparationTime: 10,
        spiceLevel: 0,
        isAvailable: true,
      },
      {
        name: "Basmati Rice",
        description: "Aromatic long-grain rice",
        price: "60",
        category: "Rice",
        dietaryTags: ["Vegetarian", "Vegan", "Gluten-Free"],
        nutritionInfo: { calories: 200, protein: 4, carbs: 45, fat: 1 },
        preparationTime: 8,
        spiceLevel: 0,
        isAvailable: true,
      },
    ],
    "Zinger": [
      {
        name: "Zinger Burger",
        description: "Crispy fried chicken patty with spicy mayo and lettuce",
        price: "220",
        category: "Burgers",
        allergens: ["Gluten", "Eggs"],
        nutritionInfo: { calories: 480, protein: 25, carbs: 35, fat: 28 },
        preparationTime: 12,
        spiceLevel: 3,
        isAvailable: true,
        isPopular: true,
      },
      {
        name: "Hot Wings",
        description: "Spicy chicken wings with buffalo sauce",
        price: "280",
        category: "Starters",
        allergens: ["Eggs"],
        nutritionInfo: { calories: 350, protein: 28, carbs: 8, fat: 24 },
        preparationTime: 15,
        spiceLevel: 4,
        isAvailable: true,
        isPopular: true,
      },
      {
        name: "Chicken Popcorn",
        description: "Bite-sized crispy chicken pieces",
        price: "180",
        category: "Starters",
        allergens: ["Gluten", "Eggs"],
        nutritionInfo: { calories: 320, protein: 20, carbs: 18, fat: 20 },
        preparationTime: 10,
        spiceLevel: 2,
        isAvailable: true,
      },
      {
        name: "Loaded Fries",
        description: "Crispy fries topped with cheese, chicken, and jalapeños",
        price: "160",
        category: "Sides",
        allergens: ["Dairy", "Gluten"],
        nutritionInfo: { calories: 420, protein: 15, carbs: 45, fat: 22 },
        preparationTime: 8,
        spiceLevel: 2,
        isAvailable: true,
      },
      {
        name: "Pepsi",
        description: "Chilled cola drink",
        price: "50",
        category: "Beverages",
        dietaryTags: ["Vegan"],
        nutritionInfo: { calories: 150, protein: 0, carbs: 39, fat: 0 },
        preparationTime: 2,
        spiceLevel: 0,
        isAvailable: true,
      },
    ],
    "Butty Sandwich": [
      {
        name: "Club Sandwich",
        description: "Triple-layered sandwich with chicken, bacon, lettuce, and tomato",
        price: "250",
        category: "Sandwiches",
        allergens: ["Gluten", "Eggs"],
        nutritionInfo: { calories: 520, protein: 32, carbs: 38, fat: 28 },
        preparationTime: 12,
        spiceLevel: 0,
        isAvailable: true,
        isPopular: true,
      },
      {
        name: "Grilled Chicken Wrap",
        description: "Marinated chicken with fresh vegetables in tortilla wrap",
        price: "220",
        category: "Wraps",
        allergens: ["Gluten"],
        nutritionInfo: { calories: 380, protein: 28, carbs: 32, fat: 18 },
        preparationTime: 10,
        spiceLevel: 1,
        isAvailable: true,
      },
      {
        name: "Veggie Deluxe Burger",
        description: "Plant-based patty with avocado and sprouts",
        price: "200",
        category: "Burgers",
        dietaryTags: ["Vegetarian"],
        allergens: ["Gluten", "Soy"],
        nutritionInfo: { calories: 350, protein: 18, carbs: 42, fat: 15 },
        preparationTime: 10,
        spiceLevel: 0,
        isAvailable: true,
      },
      {
        name: "Panini Italiano",
        description: "Grilled panini with mozzarella, tomato, and basil",
        price: "180",
        category: "Sandwiches",
        dietaryTags: ["Vegetarian"],
        allergens: ["Gluten", "Dairy"],
        nutritionInfo: { calories: 320, protein: 16, carbs: 28, fat: 18 },
        preparationTime: 8,
        spiceLevel: 0,
        isAvailable: true,
      },
      {
        name: "Fresh Orange Juice",
        description: "Freshly squeezed orange juice",
        price: "80",
        category: "Beverages",
        dietaryTags: ["Vegetarian", "Vegan"],
        nutritionInfo: { calories: 110, protein: 2, carbs: 26, fat: 0 },
        preparationTime: 3,
        spiceLevel: 0,
        isAvailable: true,
      },
    ],
    "Duck Donald": [
      {
        name: "Peking Duck",
        description: "Traditional Chinese roasted duck with pancakes and hoisin sauce",
        price: "480",
        category: "Main Course",
        allergens: ["Gluten", "Soy"],
        nutritionInfo: { calories: 550, protein: 35, carbs: 25, fat: 35 },
        preparationTime: 30,
        spiceLevel: 1,
        isAvailable: true,
        isPopular: true,
      },
      {
        name: "Chicken Hakka Noodles",
        description: "Stir-fried noodles with vegetables and chicken",
        price: "280",
        category: "Noodles",
        allergens: ["Gluten", "Soy"],
        nutritionInfo: { calories: 420, protein: 22, carbs: 45, fat: 18 },
        preparationTime: 15,
        spiceLevel: 2,
        isAvailable: true,
        isPopular: true,
      },
      {
        name: "Sweet and Sour Pork",
        description: "Crispy pork with bell peppers in tangy sauce",
        price: "320",
        category: "Main Course",
        allergens: ["Gluten", "Soy"],
        nutritionInfo: { calories: 380, protein: 25, carbs: 35, fat: 18 },
        preparationTime: 20,
        spiceLevel: 1,
        isAvailable: true,
      },
      {
        name: "Vegetable Fried Rice",
        description: "Wok-tossed rice with mixed vegetables and soy sauce",
        price: "200",
        category: "Rice",
        dietaryTags: ["Vegetarian"],
        allergens: ["Soy"],
        nutritionInfo: { calories: 320, protein: 8, carbs: 55, fat: 10 },
        preparationTime: 12,
        spiceLevel: 1,
        isAvailable: true,
      },
      {
        name: "Hot and Sour Soup",
        description: "Traditional Chinese soup with tofu and mushrooms",
        price: "120",
        category: "Soups",
        dietaryTags: ["Vegetarian"],
        allergens: ["Soy"],
        nutritionInfo: { calories: 80, protein: 4, carbs: 12, fat: 2 },
        preparationTime: 8,
        spiceLevel: 2,
        isAvailable: true,
      },
    ],
    "Shakes & Desserts": [
      {
        name: "Chocolate Brownie Sundae",
        description: "Warm brownie with vanilla ice cream and chocolate sauce",
        price: "180",
        category: "Desserts",
        dietaryTags: ["Vegetarian"],
        allergens: ["Gluten", "Dairy", "Eggs", "Nuts"],
        nutritionInfo: { calories: 520, protein: 8, carbs: 65, fat: 25 },
        preparationTime: 5,
        spiceLevel: 0,
        isAvailable: true,
        isPopular: true,
      },
      {
        name: "Oreo Milkshake",
        description: "Creamy milkshake blended with Oreo cookies",
        price: "140",
        category: "Shakes",
        dietaryTags: ["Vegetarian"],
        allergens: ["Gluten", "Dairy"],
        nutritionInfo: { calories: 380, protein: 12, carbs: 55, fat: 15 },
        preparationTime: 3,
        spiceLevel: 0,
        isAvailable: true,
        isPopular: true,
      },
      {
        name: "Strawberry Cheesecake",
        description: "Rich cheesecake with fresh strawberry topping",
        price: "160",
        category: "Desserts",
        dietaryTags: ["Vegetarian"],
        allergens: ["Gluten", "Dairy", "Eggs"],
        nutritionInfo: { calories: 420, protein: 8, carbs: 45, fat: 25 },
        preparationTime: 2,
        spiceLevel: 0,
        isAvailable: true,
      },
      {
        name: "Vanilla Ice Cream",
        description: "Premium vanilla ice cream (2 scoops)",
        price: "80",
        category: "Ice Cream",
        dietaryTags: ["Vegetarian"],
        allergens: ["Dairy"],
        nutritionInfo: { calories: 200, protein: 4, carbs: 25, fat: 10 },
        preparationTime: 1,
        spiceLevel: 0,
        isAvailable: true,
      },
      {
        name: "Mango Kulfi",
        description: "Traditional Indian frozen dessert with mango flavor",
        price: "100",
        category: "Ice Cream",
        dietaryTags: ["Vegetarian"],
        allergens: ["Dairy", "Nuts"],
        nutritionInfo: { calories: 180, protein: 6, carbs: 22, fat: 8 },
        preparationTime: 1,
        spiceLevel: 0,
        isAvailable: true,
      },
    ],
    "Yurish Drinks": [
      {
        name: "Green Detox Smoothie",
        description: "Spinach, kale, apple, and ginger power smoothie",
        price: "120",
        category: "Smoothies",
        dietaryTags: ["Vegetarian", "Vegan", "Gluten-Free"],
        nutritionInfo: { calories: 150, protein: 4, carbs: 32, fat: 1 },
        preparationTime: 5,
        spiceLevel: 0,
        isAvailable: true,
        isPopular: true,
      },
      {
        name: "Fresh Watermelon Juice",
        description: "Refreshing watermelon juice with mint",
        price: "80",
        category: "Fresh Juices",
        dietaryTags: ["Vegetarian", "Vegan", "Gluten-Free"],
        nutritionInfo: { calories: 90, protein: 1, carbs: 22, fat: 0 },
        preparationTime: 3,
        spiceLevel: 0,
        isAvailable: true,
      },
      {
        name: "Protein Berry Blast",
        description: "Mixed berries with protein powder and almond milk",
        price: "160",
        category: "Smoothies",
        dietaryTags: ["Vegetarian", "Gluten-Free"],
        allergens: ["Nuts"],
        nutritionInfo: { calories: 220, protein: 20, carbs: 25, fat: 6 },
        preparationTime: 4,
        spiceLevel: 0,
        isAvailable: true,
        isPopular: true,
      },
      {
        name: "Coconut Water",
        description: "Fresh tender coconut water",
        price: "60",
        category: "Natural Drinks",
        dietaryTags: ["Vegetarian", "Vegan", "Gluten-Free"],
        nutritionInfo: { calories: 45, protein: 2, carbs: 9, fat: 0 },
        preparationTime: 1,
        spiceLevel: 0,
        isAvailable: true,
      },
      {
        name: "Lemon Ginger Shot",
        description: "Immunity boosting shot with lemon, ginger, and turmeric",
        price: "40",
        category: "Wellness Shots",
        dietaryTags: ["Vegetarian", "Vegan", "Gluten-Free"],
        nutritionInfo: { calories: 25, protein: 1, carbs: 6, fat: 0 },
        preparationTime: 2,
        spiceLevel: 3,
        isAvailable: true,
      },
    ],
  };

  for (const restaurant of restaurants) {
    const items = menuItems[restaurant.name];
    if (items) {
      for (const item of items) {
        await storage.createMenuItem({
          ...item,
          restaurantId: restaurant.id,
        });
      }
    }
  }
}

export async function seedDatabase() {
  try {
    console.log("Seeding restaurants...");
    const restaurants = await seedRestaurants();
    
    console.log("Seeding menu items...");
    await seedMenuItems(restaurants);
    
    console.log("Database seeded successfully!");
    return { restaurants };
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
}